name: Perform CICD Operations on Console Based Java Application
on: push
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Checking Cloned/Not 
        run: |
          ls
          pwd
          ls -ltra
          tree