name: Perform CICD Operations on Console Based Java Application
on: 
  workflow_dispatch:
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Config Tools(JAVA, MVN)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 2. Config Tools(Terraform)
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: 3. Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven  # Install Maven

      - name: 4. Check Java and Maven Versions
        run: |
          java -version
          javac -version
          mvn --version
          terraform --version

      - name: 5. Clone Project
        uses: actions/checkout@v3     

      - name: 6. Clean Project
        run: mvn clean

      - name: 7. Build & Test Project
        run: mvn package 
      
      - name: 8. Infrastructure Provisioning(Initialize)
        run: terraform init

      - name: 9. Infrastructure Provisioning(Plan)
        run: terraform plan 

      - name: 10. Infrastructure Provisioning(Plan)
        run: terraform apply -auto-approve -input=false

      - name: 11. Deploy and Run Project
        run: |
          cd target/classes
          java com.mycompany.app.Calculator
